#!/bin/bash

POKER_VERSION="0.1"
POKER_NAME="$0"
POKER_HOME=~/.poker/

# TODO(timgreen): opt for POKER_HOME
# TODO(timgreen): command for setup
# TODO(timgreen): command for config

cmd_help() {
  cat << EOF
usage: $POKER_NAME [options...] <command> [<args>]

commands:

   list       List managed packages
   fetch      Get package from repo
   push       Push new package to repo
   version    Show poker version
   help       Show this help
EOF
}

cmd_version() {
  echo "poker version $POKER_VERSION"
}

command=$1
shift

case $command in
  version)  cmd_version;;
  help)     cmd_help;;
  *)        cmd_help
	    exit 2;;
esac
