#!/bin/bash
# vim: set foldmethod=marker shiftwidth=2 st=2 ts=2:

POKER_VERSION="0.1"
POKER_NAME="$0"
POKER_HOME=$HOME/.poker/
POKER_REPO_URL=""

# TODO(timgreen): opt for POKER_HOME
# TODO(timgreen): command for setup
# TODO(timgreen): command for config

## lib {{{

config_path() {
  readlink -m "$POKER_HOME/config"
}

repo_path() {
  readlink -m "$POKER_HOME/repo/"
}

tmp_repo_path() {
  readlink -m "$POKER_HOME/tmp_repo/"
}

read_config() {
  [ -r "$(config_path)" ] || { echo "Config not found: $(config_path)"; exit 1; }
  POKER_REPO_URL=$(git config -f $(config_path) --get config.repo)
  (( $? != 0 )) && echo "Error when reading 'config.repo' from config" && exit 2
}

prepare_repo() {
  [ -r "$(repo_path)" ] && return

  echo "Init poker repo ..."
  cd "$(dirname $(repo_path))"
  git clone --bare $POKER_REPO_URL "$(basename $(repo_path))"
}

## }}} lib

## Commands {{{

cmd_help() {
  cat << EOF
usage: $POKER_NAME [options...] <command> [<args>]

commands:

   sync       Sync with remote repo
   list       List managed packages
   fetch      Get package from repo
   push       Push new package to repo
   version    Show poker version
   help       Show this help
EOF
}

cmd_version() {
  echo "poker version $POKER_VERSION"
}

cmd_list() {
  read_config
  prepare_repo

  if (( $# == 0 )); then
    echo "Avaliable packages:"
    GIT_DIR="$(repo_path)" git ls-remote -h origin | sed 's/^.\+\srefs\/heads\//  /' |  \
        grep -v '\bmaster$'

    exit 0
  elif (( $# == 1)); then
    pkg_name="$1"
    echo "Avaliable versions for package '$pkg_name':"
    GIT_DIR="$(repo_path)" git ls-remote --exit-code -t origin "$pkg_name/*" | sed "s/^.\+\srefs\/tags\/$pkg_name\//  /"
    # TODO:
  else
    cmd_help list
    exit 1
  fi
}

cmd_sync() {
  read_config
  prepare_repo

  GIT_DIR="$(repo_path)" git fetch --progress
  GIT_DIR="$(repo_path)" git fetch --tags --progress
}

cmd_fetch() {
  read_config
  prepare_repo

  if (( $# != 3 )); then
    cmd_help fetch
    exit 1
  fi

  pkg_name="$1"
  version="$2"
  output="$3"

  GIT_DIR="$(repo_path)" git fetch origin "$pkg_name/$version" &> /dev/null
  (( $? != 0 )) && { echo "Can not found package $pkg_name with version $version"; exit 1; }

  GIT_DIR="$(repo_path)" git archive --format=tar -o "$output" "$pkg_name/$version"
}

cmd_push() {
  cmd_sync

  if (( $# != 3 )); then
    cmd_help push
    exit 1
  fi

  pkg_name="$1"
  version="$2"
  pkg_dir=$(readlink -m "$3")

  set -e
  rm -fr "$(tmp_repo_path)"
  mkdir -p "$(tmp_repo_path)"
  cd "$(tmp_repo_path)"
  set +e
  git init
  git remote add poker_local "$(repo_path)"
  git remote add repo "$POKER_REPO_URL"
  git checkout -B $pkg_name
  git fetch poker_local $pkg_name
  git fetch repo $pkg_name || git fetch repo master
  git reset --hard FETCH_HEAD
  git rm -fr *
  cp -r "$pkg_dir/"* .
  git add *
  git commit --allow-empty -m "$pkg_name:$version"
  git tag "$pkg_name/$version"
  git push --tags repo $pkg_name:$pkg_name
}

## }}} Commands

## main {{{
command=$1
shift

case $command in
  list)     cmd_list "$@";;
  sync)     cmd_sync;;
  fetch)    cmd_fetch "$@";;
  push)     cmd_push "$@";;
  version)  cmd_version;;
  help)     cmd_help "$@";;
  *)        cmd_help
            exit 2;;
esac
## }}} main
